### ISSUE TITLE
Flemmar no longer works with sonarr v4 and its forks becuase initialize.js has been moved to initialize.json

### ISSUE THREAD

**Issue by Laikar** [Flemmarr/Flemmarr#15]
On all the arr apps based on sonar v3, you can obtain info about the api via /initialize.js, but starting in sonarr v4 it is obtained on the /initialize.json path, and since Flemmar currently asks for that information on /initialize.js it fails when configuring newer arr apps.

**Comment by PierreMesure** [comment]
Hi @Laikar, that's unfortunate!

I'm not using Flemmarr at the moment and I don't think I'll have time to fix this through September. Do you think you (or someone else?) could have a look? A PR would be welcome! 🤗

**Comment by AidanHilt** [comment]
@PierreMesure can I ask you to take a look at my PR and let me know if it needs any changes? https://github.com/Flemmarr/Flemmarr/pull/16
