### ISSUE TITLE
Enhancement Make amd64 version for docker pull

### ISSUE THREAD

**Issue by bryceprutsos** [Flemmarr/Flemmarr#6]
Enhancement Make amd64 version for docker pull

**Comment by PierreMesure** [comment]
Oh I didn't even realised it wasn't! I'm using a Mac with ARM processor.

I'll try to do it using Github Actions, it shouldn't be too hard?

**Comment by PierreMesure** [comment]
Well that was easy!

The image is now compiled for two platforms, *linux/amd64* and *linux/arm64* and *linux/arm/v7*, the same as the popular images compiled by linuxserver.io (see for [Lidarr](https://hub.docker.com/r/linuxserver/lidarr/tags)). If anyone wants more platforms, just let me know!
